#:schema node_modules/wrangler/config-schema.json
name = "edu-synthesis"
main = "src/index.tsx"
compatibility_date = "2025-01-28"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true

[observability]
enabled = true

[build]
command = "npm run build-css"
watch_dir = "./src"

[assets]
directory = "./assets"

[[workflows]]
name = "content-generation-workflow"
binding = "CONTENT_GENERATION_WORKFLOW"
class_name = "ContentGenerationWorkflow"

[[d1_databases]]
binding = "DB"
database_name = "edu-synthesis"
database_id = "96347da8-8a3d-4ba9-b2f6-9994783b66cc"

[browser]
binding = "BROWSER"
